import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
import { Header } from 'app/components/shared/Header'
import { Description } from "app/components/home/Description"
import { Hero } from "app/components/home/Hero"
import { Footer } from 'app/components/shared/Footer'
import 'app/sass/globals.sass'

const roboto = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: 'Fake Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        <Hero />
        <Description />
        {children}
        <Footer />
      </body>
    </html>
  )
}
